<?php

namespace Werk365\IdentityDocuments\Mrz;

class Mrz
{
    protected array $TD1;
    protected array $TD2;
    protected array $TD3;
    protected array $MRVA;
    protected array $MRVB;
    protected array $keys;
    protected array $values;
    protected array $countries;
    public string $type = '';

    public function __construct()
    {
        $this->countries = [
    'ABW'=>'Aruba',
    'AFG'=>'Afghanistan',
    'AGO'=>'Angola',
    'AIA'=>'Anguilla',
    'ALA'=>'Åland Islands',
    'ALB'=>'Albania',
    'AND'=>'Andorra',
    'ARE'=>'United Arab Emirates',
    'ARG'=>'Argentina',
    'ARM'=>'Armenia',
    'ASM'=>'American Samoa',
    'ATA'=>'Antarctica',
    'ATF'=>'French Southern Territories',
    'ATG'=>'Antigua and Barbuda',
    'AUS'=>'Australia',
    'AUT'=>'Austria',
    'AZE'=>'Azerbaijan',
    'BDI'=>'Burundi',
    'BEL'=>'Belgium',
    'BEN'=>'Benin',
    'BES'=>'Bonaire, Sint Eustatius and Saba',
    'BFA'=>'Burkina Faso',
    'BGD'=>'Bangladesh',
    'BGR'=>'Bulgaria',
    'BHR'=>'Bahrain',
    'BHS'=>'Bahamas',
    'BIH'=>'Bosnia and Herzegovina',
    'BLM'=>'Saint Barthélemy',
    'BLR'=>'Belarus',
    'BLZ'=>'Belize',
    'BMU'=>'Bermuda',
    'BOL'=>'Bolivia, Plurinational State of',
    'BRA'=>'Brazil',
    'BRB'=>'Barbados',
    'BRN'=>'Brunei Darussalam',
    'BTN'=>'Bhutan',
    'BVT'=>'Bouvet Island',
    'BWA'=>'Botswana',
    'CAF'=>'Central African Republic',
    'CAN'=>'Canada',
    'CCK'=>'Cocos (Keeling) Islands',
    'CHE'=>'Switzerland',
    'CHL'=>'Chile',
    'CHN'=>'China',
    'CIV'=>'Côte d\'Ivoire',
    'CMR'=>'Cameroon',
    'COD'=>'Congo, the Democratic Republic of the',
    'COG'=>'Congo',
    'COK'=>'Cook Islands',
    'COL'=>'Colombia',
    'COM'=>'Comoros',
    'CPV'=>'Cape Verde',
    'CRI'=>'Costa Rica',
    'CUB'=>'Cuba',
    'CUW'=>'Curaçao',
    'CXR'=>'Christmas Island',
    'CYM'=>'Cayman Islands',
    'CYP'=>'Cyprus',
    'CZE'=>'Czech Republic',
    'DEU'=>'Germany',
    'DJI'=>'Djibouti',
    'DMA'=>'Dominica',
    'DNK'=>'Denmark',
    'DOM'=>'Dominican Republic',
    'DZA'=>'Algeria',
    'ECU'=>'Ecuador',
    'EGY'=>'Egypt',
    'ERI'=>'Eritrea',
    'ESH'=>'Western Sahara',
    'ESP'=>'Spain',
    'EST'=>'Estonia',
    'ETH'=>'Ethiopia',
    'FIN'=>'Finland',
    'FJI'=>'Fiji',
    'FLK'=>'Falkland Islands (Malvinas)',
    'FRA'=>'France',
    'FRO'=>'Faroe Islands',
    'FSM'=>'Micronesia, Federated States of',
    'GAB'=>'Gabon',
    'GBR'=>'United Kingdom',
    'GEO'=>'Georgia',
    'GGY'=>'Guernsey',
    'GHA'=>'Ghana',
    'GIB'=>'Gibraltar',
    'GIN'=>'Guinea',
    'GLP'=>'Guadeloupe',
    'GMB'=>'Gambia',
    'GNB'=>'Guinea-Bissau',
    'GNQ'=>'Equatorial Guinea',
    'GRC'=>'Greece',
    'GRD'=>'Grenada',
    'GRL'=>'Greenland',
    'GTM'=>'Guatemala',
    'GUF'=>'French Guiana',
    'GUM'=>'Guam',
    'GUY'=>'Guyana',
    'HKG'=>'Hong Kong',
    'HMD'=>'Heard Island and McDonald Islands',
    'HND'=>'Honduras',
    'HRV'=>'Croatia',
    'HTI'=>'Haiti',
    'HUN'=>'Hungary',
    'IDN'=>'Indonesia',
    'IMN'=>'Isle of Man',
    'IND'=>'India',
    'IOT'=>'British Indian Ocean Territory',
    'IRL'=>'Ireland',
    'IRN'=>'Iran, Islamic Republic of',
    'IRQ'=>'Iraq',
    'ISL'=>'Iceland',
    'ISR'=>'Israel',
    'ITA'=>'Italy',
    'JAM'=>'Jamaica',
    'JEY'=>'Jersey',
    'JOR'=>'Jordan',
    'JPN'=>'Japan',
    'KAZ'=>'Kazakhstan',
    'KEN'=>'Kenya',
    'KGZ'=>'Kyrgyzstan',
    'KHM'=>'Cambodia',
    'KIR'=>'Kiribati',
    'KNA'=>'Saint Kitts and Nevis',
    'KOR'=>'Korea, Republic of',
    'KWT'=>'Kuwait',
    'LAO'=>'Lao People\'s Democratic Republic',
    'LBN'=>'Lebanon',
    'LBR'=>'Liberia',
    'LBY'=>'Libya',
    'LCA'=>'Saint Lucia',
    'LIE'=>'Liechtenstein',
    'LKA'=>'Sri Lanka',
    'LSO'=>'Lesotho',
    'LTU'=>'Lithuania',
    'LUX'=>'Luxembourg',
    'LVA'=>'Latvia',
    'MAC'=>'Macao',
    'MAF'=>'Saint Martin (French part)',
    'MAR'=>'Morocco',
    'MCO'=>'Monaco',
    'MDA'=>'Moldova, Republic of',
    'MDG'=>'Madagascar',
    'MDV'=>'Maldives',
    'MEX'=>'Mexico',
    'MHL'=>'Marshall Islands',
    'MKD'=>'Macedonia, the former Yugoslav Republic of',
    'MLI'=>'Mali',
    'MLT'=>'Malta',
    'MMR'=>'Myanmar',
    'MNE'=>'Montenegro',
    'MNG'=>'Mongolia',
    'MNP'=>'Northern Mariana Islands',
    'MOZ'=>'Mozambique',
    'MRT'=>'Mauritania',
    'MSR'=>'Montserrat',
    'MTQ'=>'Martinique',
    'MUS'=>'Mauritius',
    'MWI'=>'Malawi',
    'MYS'=>'Malaysia',
    'MYT'=>'Mayotte',
    'NAM'=>'Namibia',
    'NCL'=>'New Caledonia',
    'NER'=>'Niger',
    'NFK'=>'Norfolk Island',
    'NGA'=>'Nigeria',
    'NIC'=>'Nicaragua',
    'NIU'=>'Niue',
    'NLD'=>'Netherlands',
    'NOR'=>'Norway',
    'NPL'=>'Nepal',
    'NRU'=>'Nauru',
    'NZL'=>'New Zealand',
    'OMN'=>'Oman',
    'PAK'=>'Pakistan',
    'PAN'=>'Panama',
    'PCN'=>'Pitcairn',
    'PER'=>'Peru',
    'PHL'=>'Philippines',
    'PLW'=>'Palau',
    'PNG'=>'Papua New Guinea',
    'POL'=>'Poland',
    'PRI'=>'Puerto Rico',
    'PRK'=>'Korea, Democratic People\'s Republic of',
    'PRT'=>'Portugal',
    'PRY'=>'Paraguay',
    'PSE'=>'Palestinian Territory, Occupied',
    'PYF'=>'French Polynesia',
    'QAT'=>'Qatar',
    'REU'=>'Réunion',
    'ROU'=>'Romania',
    'RUS'=>'Russian Federation',
    'RWA'=>'Rwanda',
    'SAU'=>'Saudi Arabia',
    'SDN'=>'Sudan',
    'SEN'=>'Senegal',
    'SGP'=>'Singapore',
    'SGS'=>'South Georgia and the South Sandwich Islands',
    'SHN'=>'Saint Helena, Ascension and Tristan da Cunha',
    'SJM'=>'Svalbard and Jan Mayen',
    'SLB'=>'Solomon Islands',
    'SLE'=>'Sierra Leone',
    'SLV'=>'El Salvador',
    'SMR'=>'San Marino',
    'SOM'=>'Somalia',
    'SPM'=>'Saint Pierre and Miquelon',
    'SRB'=>'Serbia',
    'SSD'=>'South Sudan',
    'STP'=>'Sao Tome and Principe',
    'SUR'=>'Suriname',
    'SVK'=>'Slovakia',
    'SVN'=>'Slovenia',
    'SWE'=>'Sweden',
    'SWZ'=>'Swaziland',
    'SXM'=>'Sint Maarten (Dutch part)',
    'SYC'=>'Seychelles',
    'SYR'=>'Syrian Arab Republic',
    'TCA'=>'Turks and Caicos Islands',
    'TCD'=>'Chad',
    'TGO'=>'Togo',
    'THA'=>'Thailand',
    'TJK'=>'Tajikistan',
    'TKL'=>'Tokelau',
    'TKM'=>'Turkmenistan',
    'TLS'=>'Timor-Leste',
    'TON'=>'Tonga',
    'TTO'=>'Trinidad and Tobago',
    'TUN'=>'Tunisia',
    'TUR'=>'Turkey',
    'TUV'=>'Tuvalu',
    'TWN'=>'Taiwan, Province of China',
    'TZA'=>'Tanzania, United Republic of',
    'UGA'=>'Uganda',
    'UKR'=>'Ukraine',
    'UMI'=>'United States Minor Outlying Islands',
    'URY'=>'Uruguay',
    'USA'=>'United States',
    'UZB'=>'Uzbekistan',
    'VAT'=>'Holy See (Vatican City State)',
    'VCT'=>'Saint Vincent and the Grenadines',
    'VEN'=>'Venezuela, Bolivarian Republic of',
    'VGB'=>'Virgin Islands, British',
    'VIR'=>'Virgin Islands, U.S.',
    'VNM'=>'Viet Nam',
    'VUT'=>'Vanuatu',
    'WLF'=>'Wallis and Futuna',
    'WSM'=>'Samoa',
    'YEM'=>'Yemen',
    'ZAF'=>'South Africa',
    'ZMB'=>'Zambia',
    'ZWE'=>'Zimbabwe',
    'D' => 'Germany',
    'EUE' => 'European Union',
    'GBD' => 'British Overseas Territories Citizen',
    'GBN' => 'British National (Overseas)',
    'GBO' => 'British Overseas Citizen',
    'GBP' => 'British Protected Person',
    'GBS' => 'British Subject',
    'UNA' => 'specialized agency of the United Nations',
    'UNK' => 'Resident of Kosovo',
    'UNO' => 'United Nations organization',
    'XBA' => 'African Development Bank',
    'XIM' => 'African Export–Import Bank',
    'XCC' => 'Caribbean Community or one of its emissaries',
    'XCO' => 'Common Market for Eastern and Southern Africa',
    'XEC' => 'Economic Community of West African States',
    'XPO' => 'International Criminal Police Organization',
    'XOM' => 'Sovereign Military Order of Malta',
    'XXA' => 'Stateless person',
    'XXB' => 'Refugee',
    'XXC' => 'Refugee',
    'XXX' => 'Unspecified nationality',
];
        $this->loadConfig();
    }

    private function loadConfig()
    {
        $this->TD3 = [
            'checks' => [
                53 => [[44, 9]],
                63 => [[57, 6]],
                71 => [[65, 6]],
                86 => [[72, 14]],
                87 => [[44, 10], [57, 7], [65, 22]],
            ],
            'length' => 88,
        ];

        $this->TD2 = [
            'checks' => [
                45 => [[36, 9]],
                55 => [[49, 6]],
                64 => [[58, 6]],
                71 => [[44, 10], [49, 7], [58, 12]],
            ],
            'length' => 72,
        ];

        $this->TD1 = [
            'checks' => [
                14 => [[5, 9]],
                36 => [[30, 6]],
                44 => [[38, 6]],
                59 => [[5, 25], [30, 7], [38, 7], [48, 10]],
            ],
            'length' => 90,
        ];

        $this->MRVA = [
            'checks' => [
                53 => [[44, 9]],
                63 => [[57, 6]],
                71 => [[65, 6]],
                86 => [[72, 14]],
                87 => [[44, 10], [57, 7], [65, 22]],
            ],
            'length' => 88,
        ];

        $this->MRVB = [
            'checks' => [
                53 => [[44, 9]],
                63 => [[57, 6]],
                71 => [[65, 6]],
                86 => [[72, 14]],
                87 => [[44, 10], [57, 7], [65, 22]],
            ],
            'length' => 88,
        ];

        $this->keys = [
            'P' => ['TD3' => &$this->TD3['checks']],
            'I' => ['TD1' => &$this->TD1['checks'], 'TD2' => &$this->TD2['checks']],
            'A' => ['TD1' => &$this->TD1['checks'], 'TD2' => &$this->TD2['checks']],
            'C' => ['TD1' => &$this->TD1['checks'], 'TD2' => &$this->TD2['checks']],
            'V' => ['MRVA' => &$this->MRVA['checks'], 'MRVB' => &$this->MRVB['checks']],
        ];

        // values to be found in MRZ by format, [position in string, sub string length]
        $this->values = [
            'document_key' => [
                'TD1' => [0, 1],
                'TD2' => [0, 1],
                'TD3' => [0, 1],
                'MRVA' => [0, 1],
                'MRVB' => [0, 1],
            ],
            'document_type' => [
                'TD1' => [1, 1],
                'TD2' => [1, 1],
                'TD3' => [1, 1],
                'MRVA' => [1, 1],
                'MRVB' => [1, 1],
            ],
            'issuing_country' => [
                'TD1' => [2, 3],
                'TD2' => [2, 3],
                'TD3' => [2, 3],
                'MRVA' => [2, 3],
                'MRVB' => [2, 3],
            ],
            'full_name' => [
                'TD1' => [60, 30],
                'TD2' => [5, 31],
                'TD3' => [5, 39],
                'MRVA' => [5, 39],
                'MRVB' => [5, 31],
            ],
            'document_number' => [
                'TD1' => [5, 9],
                'TD2' => [36, 9],
                'TD3' => [44, 9],
                'MRVA' => [44, 9],
                'MRVB' => [36, 9],
            ],
            'nationality' => [
                'TD1' => [45, 3],
                'TD2' => [46, 3],
                'TD3' => [54, 3],
                'MRVA' => [54, 3],
                'MRVB' => [46, 3],
            ],
            'date_of_birth' => [
                'TD1' => [30, 6],
                'TD2' => [49, 6],
                'TD3' => [57, 6],
                'MRVA' => [57, 6],
                'MRVB' => [49, 6],
            ],
            'sex' => [
                'TD1' => [37, 1],
                'TD2' => [56, 1],
                'TD3' => [64, 1],
                'MRVA' => [64, 1],
                'MRVB' => [56, 1],
            ],
            'expiration_date' => [
                'TD1' => [38, 6],
                'TD2' => [57, 6],
                'TD3' => [65, 6],
                'MRVA' => [65, 6],
                'MRVB' => [57, 6],
            ],
            'personal_number' => [
                'TD1' => [],
                'TD2' => [],
                'TD3' => [72, 14],
                'MRVA' => [],
                'MRVB' => [],
            ],
            'optional_data_row_1' => [
                'TD1' => [15, 15],
                'TD2' => [],
                'TD3' => [],
                'MRVA' => [],
                'MRVB' => [],
            ],
            'optional_data_row_2' => [
                'TD1' => [48, 11],
                'TD2' => [64, 7],
                'TD3' => [],
                'MRVA' => [72, 16],
                'MRVB' => [64, 8],
            ],
        ];
    }
}
